name: image_labeling_app
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.2.0
  tflite_flutter: ^0.10.0
  firebase_core: ^3.8.0
  firebase_ml_model_downloader: ^0.3.1+5
  image_picker: ^0.8.7
  flutter_image_compress: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/model.tflite
    - assets/labels.txt
